"use client";

import { useCallback, useEffect, useState } from "react";

type PriceSource = { id: string; name: string; price: number | null; previousPrice?: number | null; url: string; status: "live" | "unavailable"; updatedAt: string | null; domain?: string; note?: string };
type Market = { averagePrice: number | null; sources: PriceSource[] };
type PriceResponse = { gold: Market; dollar: Market; updatedAt: string; refreshAfterSeconds: number };
const REFRESH_SECONDS = 20;
const fallback: PriceResponse = { gold: { averagePrice: null, sources: [
  { id: "talasea", name: "طلاسی", price: null, url: "https://talasea.ir/", status: "unavailable", updatedAt: null, domain: "talasea.ir" },
  { id: "daric", name: "داریک", price: null, url: "https://daric.gold/", status: "unavailable", updatedAt: null, domain: "daric.gold" },
  { id: "milli", name: "میلی", price: null, url: "https://milli.gold/", status: "unavailable", updatedAt: null, domain: "milli.gold" },
  { id: "tgju", name: "شبکه طلا و ارز", price: null, url: "https://www.tgju.org/profile/geram18", status: "unavailable", updatedAt: null, domain: "tgju.org" },
  { id: "iranjib", name: "ایران‌جیب", price: null, url: "https://www.iranjib.ir/showgroup/23/gold/", status: "unavailable", updatedAt: null, domain: "iranjib.ir" },
] }, dollar: { averagePrice: null, sources: [
  { id: "bitpin", name: "بیت‌پین", price: null, url: "https://bitpin.ir/", status: "unavailable", updatedAt: null, domain: "bitpin.ir" },
  { id: "tabdeal", name: "تبدیل", price: null, url: "https://tabdeal.org/live/currency", status: "unavailable", updatedAt: null, domain: "tabdeal.org" },
  { id: "nobitex", name: "نوبیتکس", price: null, url: "https://nobitex.ir/", status: "unavailable", updatedAt: null, domain: "nobitex.ir" },
  { id: "wallex", name: "والکس", price: null, url: "https://wallex.ir/", status: "unavailable", updatedAt: null, domain: "wallex.ir" },
  { id: "raastin", name: "راستین", price: null, url: "https://raastin.com/", status: "unavailable", updatedAt: null, domain: "raastin.com" },
] }, updatedAt: "", refreshAfterSeconds: REFRESH_SECONDS };
function amount(value: number | null, unit: string) { return value === null || !Number.isFinite(value) ? "—" : `${new Intl.NumberFormat("fa-IR").format(Math.round(value))} ${unit}`; }
function timestamp(value: string | null) { const date = value ? new Date(value) : null; return !date || Number.isNaN(date.getTime()) ? "نامشخص" : new Intl.DateTimeFormat("fa-IR", { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(date); }
function withPrevious(next: PriceResponse, current: PriceResponse | null): PriceResponse { const previous = new Map([...(current?.gold.sources ?? []), ...(current?.dollar.sources ?? [])].map((source) => [source.id, source.price])); const addPrevious = (market: Market) => ({ ...market, sources: market.sources.map((source) => ({ ...source, previousPrice: previous.get(source.id) ?? null })) }); return { ...next, gold: addPrevious(next.gold), dollar: addPrevious(next.dollar) }; }
function SourceLogo({ source }: { source: PriceSource }) { const [failed, setFailed] = useState(false); const domain = source.domain ?? new URL(source.url).hostname; return <span className="source-logo" aria-hidden="true">{!failed && <img src={`https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=64`} alt="" onError={() => setFailed(true)} />}{failed && <b>{source.name.trim().slice(0, 1)}</b>}</span>; }
function MarketPanel({ market, title, titleEnglish, unit, tone }: { market: Market; title: string; titleEnglish: string; unit: string; tone: "gold" | "dollar" }) {
  const liveCount = market.sources.filter((source) => source.status === "live" && source.price !== null).length;
  const sortedSources = [...market.sources].sort((a, b) => (b.price ?? -1) - (a.price ?? -1));
  return <section className={`market-panel ${tone}`} aria-labelledby={`${tone}-title`}><div className="market-topline"><div><p className="market-kicker">{titleEnglish}</p><h2 id={`${tone}-title`}>{title}</h2></div><span className="market-symbol" aria-hidden="true">{tone === "gold" ? "Au" : "$"}</span></div><div className="market-average"><div><span>قیمت میانگین</span><strong>{amount(market.averagePrice, unit)}</strong></div><span className="source-count">{liveCount} از {market.sources.length} منبع فعال</span></div><div className="source-list" role="list">{sortedSources.map((source, index) => { const live = source.status === "live" && source.price !== null; return <article className="source-row" role="listitem" key={source.id}><span className="source-rank" aria-label={`رتبه ${index + 1}`}>{index + 1}</span><SourceLogo source={source} /><div className="source-name"><h3>{source.name}</h3><span className={`source-status ${live ? "online" : "offline"}`}>{live ? "فعال" : "ناموجود"}</span></div><div className="source-quote"><p className={live ? "source-price" : "source-price unavailable"}>{live ? amount(source.price, unit) : "قیمت در دسترس نیست"}</p>{live && <p className="previous-price">قبلی: {amount(source.previousPrice ?? null, unit)}</p>}{source.note && !live && <p className="source-note">{source.note}</p>}</div><a href={source.url} target="_blank" rel="noreferrer" aria-label={`مشاهده منبع ${source.name}`}>↗</a></article>; })}</div></section>;
}
export default function Home() {
  const [data, setData] = useState<PriceResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [remaining, setRemaining] = useState(REFRESH_SECONDS); const [theme, setTheme] = useState<"light" | "dark">("light");
  const fetchPrices = useCallback(async () => { try { const response = await fetch("/api/prices", { cache: "no-store" }); if (!response.ok) throw new Error("Price service unavailable"); const nextData = await response.json() as PriceResponse; setData((current) => withPrevious(nextData, current)); setError(false); setRemaining(REFRESH_SECONDS); } catch { setError(true); } finally { setLoading(false); } }, []);
  useEffect(() => { const saved = window.localStorage.getItem("talnama-theme"); if (saved === "dark" || saved === "light") setTheme(saved); else if (window.matchMedia("(prefers-color-scheme: dark)").matches) setTheme("dark"); }, []);
  useEffect(() => { window.localStorage.setItem("talnama-theme", theme); }, [theme]);
  useEffect(() => { void fetchPrices(); const interval = window.setInterval(() => void fetchPrices(), REFRESH_SECONDS * 1000); return () => window.clearInterval(interval); }, [fetchPrices]);
  useEffect(() => { const ticker = window.setInterval(() => setRemaining((value) => value <= 1 ? REFRESH_SECONDS : value - 1), 1000); return () => window.clearInterval(ticker); }, []);
  const prices = data ?? fallback;
  return <main className={`dashboard-shell theme-${theme}`}><div className="ambient ambient-one" /><div className="ambient ambient-two" /><section className="dashboard" aria-labelledby="page-title"><header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden="true">ن</span><span>نرخ‌نما</span></div><div className="topbar-actions"><button type="button" className="theme-toggle" onClick={() => setTheme(theme === "light" ? "dark" : "light")} aria-label={theme === "light" ? "فعال‌سازی حالت تیره" : "فعال‌سازی حالت روشن"}>{theme === "light" ? "☾" : "☀"}</button></div></header><div className="intro"><p className="eyebrow">پایش لحظه‌ای بازار ایران</p><h1 id="page-title">طلا و دلار، در یک نگاه</h1><p>قیمت میانگین منابع منتخب را ببینید؛ اطلاعات هر ۲۰ ثانیه تازه می‌شوند.</p></div><div className="update-bar" aria-live="polite"><span>آخرین بروزرسانی: {timestamp(data?.updatedAt ?? null)}</span><span>{remaining} ثانیه تا بروزرسانی</span></div>{error && <div className="notice" role="alert">دریافت قیمت‌ها فعلاً ممکن نیست؛ با بازگشت اتصال، اطلاعات خودکار بروزرسانی می‌شود.</div>}<div className="markets" aria-busy={loading}><MarketPanel market={prices.gold} title="طلای ۱۸ عیار" titleEnglish="18K GOLD · تومان / گرم" unit="تومان / گرم" tone="gold" /><MarketPanel market={prices.dollar} title="دلار آمریکا" titleEnglish="USD · تومان" unit="تومان" tone="dollar" /></div><section className="method" aria-labelledby="method-title"><span className="method-icon" aria-hidden="true">◎</span><div><h2 id="method-title">روش محاسبه</h2><p>قیمت میانگین، میانگین ساده‌ی قیمت‌های زنده است؛ منبع ناموجود در محاسبه لحاظ نمی‌شود.</p></div></section><footer><span>پایش مستقل بازار طلا و ارز</span><span>بروزرسانی خودکار هر ۲۰ ثانیه</span></footer></section></main>;
}
