"use client";
import { useCallback, useEffect, useState } from "react";
type PriceSource = { id: string; name: string; price: number | null; url: string; status: "live" | "unavailable"; updatedAt: string | null };
type PriceResponse = { pooledPrice: number | null; sources: PriceSource[]; updatedAt: string; refreshAfterSeconds: number };
const REFRESH_SECONDS = 20;
const sourceMeta: Record<string, { initial: string; color: string }> = { talasea: { initial: "ت", color: "talasea" }, daric: { initial: "د", color: "daric" }, milli: { initial: "م", color: "milli" } };
const fallbackSources: PriceSource[] = [{ id: "talasea", name: "طلاسی", price: null, url: "https://talasea.ir/", status: "unavailable", updatedAt: null }, { id: "daric", name: "داریک", price: null, url: "https://daric.gold/", status: "unavailable", updatedAt: null }, { id: "milli", name: "میلی", price: null, url: "https://milli.gold/", status: "unavailable", updatedAt: null }];
function toman(value: number | null) { return value === null || !Number.isFinite(value) ? "—" : `${new Intl.NumberFormat("fa-IR").format(Math.round(value))} تومان`; }
function timestamp(value: string | null) { const date = value ? new Date(value) : null; return !date || Number.isNaN(date.getTime()) ? "نامشخص" : new Intl.DateTimeFormat("fa-IR", { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(date); }
export default function Home() {
  const [data, setData] = useState<PriceResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [remaining, setRemaining] = useState(REFRESH_SECONDS);
  const fetchPrices = useCallback(async () => { try { const response = await fetch("/api/prices", { cache: "no-store" }); if (!response.ok) throw new Error("Price service unavailable"); const nextData = await response.json() as PriceResponse; setData(nextData); setError(false); setRemaining(nextData.refreshAfterSeconds || REFRESH_SECONDS); } catch { setError(true); } finally { setLoading(false); } }, []);
  useEffect(() => { void fetchPrices(); const refresh = window.setInterval(() => void fetchPrices(), REFRESH_SECONDS * 1000); return () => window.clearInterval(refresh); }, [fetchPrices]);
  useEffect(() => { const ticker = window.setInterval(() => setRemaining((seconds) => seconds <= 1 ? REFRESH_SECONDS : seconds - 1), 1000); return () => window.clearInterval(ticker); }, []);
  const sources = data?.sources ?? fallbackSources; const availableSources = sources.filter((source) => source.status === "live" && source.price !== null).length; const statusLabel = loading ? "در حال دریافت" : error ? "اتصال برقرار نیست" : availableSources ? "داده تازه" : "داده در دسترس نیست";
  return <main className="dashboard-shell"><div className="ambient ambient-one" /><div className="ambient ambient-two" /><section className="dashboard" aria-labelledby="page-title"><header className="topbar"><div className="brand"><span className="brand-mark" aria-hidden="true">ط</span><span>طلا‌نما</span></div><div className={`live-pill ${error ? "is-error" : ""}`} aria-live="polite"><span className="pulse" aria-hidden="true" />{statusLabel}</div></header><div className="intro"><p className="eyebrow">نمای لحظه‌ای بازار طلا</p><h1 id="page-title">قیمت تجمیعی طلای ۱۸ عیار</h1><p>میانگین قیمت‌های قابل‌دسترسی از سه منبع معتبر، هر ۲۰ ثانیه به‌روزرسانی می‌شود.</p></div><section className="hero-price" aria-live="polite" aria-busy={loading}><div className="hero-heading"><span>قیمت تجمیعی</span><span className="source-count">{availableSources} از ۳ منبع فعال</span></div><strong className={loading ? "is-loading" : ""}>{loading ? "در حال دریافت…" : toman(data?.pooledPrice ?? null)}</strong><div className="price-footnote"><span>آخرین بروزرسانی: {timestamp(data?.updatedAt ?? null)}</span><button type="button" onClick={() => void fetchPrices()} aria-label="بروزرسانی قیمت‌ها">↻ بروزرسانی</button></div></section>{error && <div className="notice" role="alert">دریافت قیمت‌ها فعلاً ممکن نیست. هنگام بازگشت اتصال، اطلاعات خودکار به‌روزرسانی می‌شود.</div>}<section className="sources-section" aria-labelledby="sources-title"><div className="section-heading"><h2 id="sources-title">منابع قیمت</h2><span>{remaining} ثانیه تا بروزرسانی</span></div><div className="source-grid">{sources.map((source) => { const meta = sourceMeta[source.id] ?? { initial: source.name[0], color: "generic" }; const isLive = source.status === "live" && source.price !== null; return <article className="source-card" key={source.id}><div className="source-card-top"><span className={`source-logo ${meta.color}`}>{meta.initial}</span><span className={`source-status ${isLive ? "online" : "offline"}`}>{isLive ? "فعال" : "ناموجود"}</span></div><h3>{source.name}</h3><p className={isLive ? "source-price" : "source-price unavailable"}>{isLive ? toman(source.price) : "قیمت در دسترس نیست"}</p><a href={source.url} target="_blank" rel="noreferrer" aria-label={`مشاهده ${source.name}`}>مشاهده منبع <span aria-hidden="true">↗</span></a></article>; })}</div></section><section className="method" aria-labelledby="method-title"><span className="method-icon" aria-hidden="true">◎</span><div><h2 id="method-title">روش محاسبه</h2><p>قیمت تجمیعی، میانگین ساده‌ی قیمت‌های زنده‌ی منابع است؛ منابع ناموجود در محاسبه لحاظ نمی‌شوند.</p></div></section><footer><span>پایش مستقل بازار طلا</span><span>بروزرسانی خودکار هر ۲۰ ثانیه</span></footer></section></main>;
}
